---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: ubuntu-golang-virtualbox
    driver:
      box: ubuntu-golang-virtualbox-test
      box_url: file:///<%= ENV['PWD'] %>/output-ubuntu-golang/package.box
      provider: virtualbox

verifier:
  name: inspec
  sudo: false

suites:
  - name: default
