---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: ubuntu-1604-golang-virtualbox
    driver:
      box: ubuntu-1604-golang-virtualbox-test
      box_url: file:///<%= ENV[PWD] =>/output-ubuntu-1604-golang/package.box
      provider: virtualbox

verifier:
  name: inspec
  sudo: false

suites:
  - name: default
